name: dev-deploy
description: dev-deploy action for the pipeline

inputs:
  CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT:
    required: true

  SERVICE_ACCOUNT_KEYFILE_JSON:
    required: true

  PROJECT_ID:
    required: true

  CLOUD_FUN_MEMORY:
    required: true

  CLOUD_FUN_REGION:
    required: true

  CLOUD_FUN_RUNTIME:
    required: true

  CLOUD_FUN_TIMEOUT:
    required: true

runs:
  using: "composite"
  steps:
    - name: Deploying image...
      shell: bash
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        gcloud beta run deploy exportgithubsk \
            --use-http2 \
            --service-account=${{ inputs.CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT }} \
            --image=europe-west1-docker.pkg.dev/vb-eva-gen/exportgithubsk-repository/exportgithubsk \
            --vpc-connector=projects/vb-eva-gen/locations/europe-west1/connectors/eva-modeller \
            --region=europe-west1 \
            --platform=managed \
            --timeout=600s \
            --concurrency=80 \
            --cpu-boost \
            --no-use-http2 \
            --allow-unauthenticated \
            --quiet \
            --vpc-egress=private-ranges-only \
            --user-output-enabled \
            --port=9090 \
            --max-instances=10 \
            --min-instances=0 \
            --cpu=2 \
            --memory=1Gi \
            --set-env-vars JAVA_TOOL_OPTIONS="-Xss256k" \
            --execution-environment=gen2 \
            --update-secrets=SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID=SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID:latest,SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET=SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET:latest

    - name: Install zip
      shell: sh
      run: |
        apk add --no-cache zip

    - name: Build the cloud function
      shell: bash
      run: |
        mkdir -p deployment
        cd BackendApp/src/functions/java
        mvn clean package
        ls -l target
        cp target/csv-to-excel-dev-function-1.0-SNAPSHOT.jar ../../../../deployment/
        cp -r src ../../../../deployment/src/
        cp pom.xml ../../../../deployment/
        cd ../../../../deployment
        zip -r ../csv-to-excel-function-deployment.zip .
        cd ..

    - name: Upload to Google Cloud Storage
      shell: bash
      run: |
        gsutil cp csv-to-excel-function-deployment.zip gs://vb-eva-gen-configuration/cloudfunctions/
    
    - name: Deploy Cloud Function
      shell: bash
      run: |
        gcloud functions deploy CSVToExcelHubFunction --gen2 --service-account=${{ inputs.CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT }} --entry-point com.vb.csvtoexcel.CSVToExcelFunction --runtime java17 --trigger-http --memory 2048MB --timeout 540s --region europe-west1 --source gs://vb-eva-gen-configuration/cfunction/csv-to-excel-function-deployment.zip
