name: dev-deploy
description: dev-deploy action for the pipeline

inputs:
  CLOUD_RUN_DEFAULT_SERVICE_ACCOUNT:
    required: true

  SERVICE_ACCOUNT_KEYFILE_JSON:
    required: true

  PROJECT_ID:
    required: true

  CLOUD_FUN_MEMORY:
    required: true

  CLOUD_FUN_REGION:
    required: true

  CLOUD_FUN_RUNTIME:
    required: true

  CLOUD_FUN_TIMEOUT:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setting up environment for build...
      shell: sh
      run: |
        apk add --no-cache git maven bash curl wget
        apk --no-cache add openjdk17-jdk
        apk add --no-cache python3 py3-pip
        
    - name: Checking out repo...
      uses: actions/checkout@v3
      with:
        ref: development
    
    - name: Building project...
      shell: sh
      run: |
        sed -i 's/${env.ARTIFACTORY_USER}/${{inputs.ARTIFACTORY_USER}}/' .m2/settings.xml
        sed -i 's/${env.ARTIFACTORY_PASS}/${{inputs.ARTIFACTORY_PASS}}/' .m2/settings.xml
        npm install -g @angular/cli

    - name: Install zip
      shell: sh
      run: |
        apk add --no-cache zip

    - name: Build the cloud function
      shell: bash
      run: |
        mkdir -p deployment
        cd BackendApp/src/functions/java
        mvn clean package
        ls -l target
        cp target/csv-to-excel-dev-function-1.0-SNAPSHOT.jar ../../../../deployment/
        cp -r src ../../../../deployment/src/
        cp pom.xml ../../../../deployment/
        cd ../../../../deployment
        zip -r ../csv-to-excel-function-deployment.zip .
        cd ..

    - name: Upload to Google Cloud Storage
      shell: bash
      run: |
        gsutil cp csv-to-excel-function-deployment.zip gs://vb-eva-gen-configuration/cloudfunctions/

    - name: Deploy Cloud Function
      shell: bash
      run: |
        gcloud functions deploy CSVToExcelDevFunction \
            --gen2 \
            --entry-point com.vb.csvtoexcel.CSVToExcelDevFunction \
            --runtime ${{inputs.CLOUD_FUN_RUNTIME}} \
            --trigger-http \
            --memory ${{inputs.CLOUD_FUN_MEMORY}} \
            --timeout ${{inputs.CLOUD_FUN_TIMEOUT}} \
            --region ${{inputs.CLOUD_FUN_REGION}} \
            --source gs://vb-eva-gen-configuration/cloudfunctions/csv-to-excel-function-deployment.zip

    - name: Deploying image...
      shell: bash
      run: |
        export CLOUDSDK_CORE_DISABLE_PROMPTS=1
        gcloud functions deploy CSVToExcelHubFunction --gen2 --entry-point com.vb.csvtoexcel.CSVToExcelFunction --runtime java17 --trigger-http --memory 2048MB --timeout 540s --region europe-west1 --source gs://vb-eva-gen-configuration/cfunction/csv-to-excel-function-deployment.zip
